---
services:

############################
# JELLYFIN	
############################

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /data:/data
    ports:
      - 8096:8096
      - 7359:7359/udp #Service Discovery
      - 1900:1900/udp #Client Discovery
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

############################
# JELLYSEERR	
############################

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

############################
# CLOUDFLARED
############################

  media-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: media-tunnel
    environment:
      - TZ=America/New_York
    command: tunnel --no-autoupdate run --token eyJhIjoiODA3NzcxNjBhOTEwMDFhNWVkMGZkMDQyMTA3NWU3YTQiLCJ0IjoiMzNhZTcyMDUtZDViMy00OThmLTg4ZDUtOTJlN2E3ZDg0YzdjIiwicyI6IlltTXdZakU1T0RZdE16WXdOUzAwTldVd0xXRTVNakl0TkRsa09ETTVORGszTkRabCJ9
    restart: unless-stopped
      
############################
